---
teleport_proxy_addr: "proxy.example.com:443"
teleport_join_method: "token"
teleport_join_token: "CHANGEME"
teleport_ca_pins: []
teleport_node_labels: {}
teleport_services:
  - ssh
teleport_version: "17"
teleport_config_path: "/etc/teleport.yaml"
teleport_data_dir: "/var/lib/teleport"
teleport_package_name: "teleport"
